### ISSUE TITLE
How to configure it?

### ISSUE THREAD

**Issue by chellem** [spnw/mpc-bar#4]
As title says.

How do I set a custom mpd server not running on the same host ?

**Comment by spnw** [comment]
Currently it's not possible, as localhost is hard-coded in. This would be easy enough to fix though. Thanks for pointing it out.

**Comment by spnw** [comment]
I've just pushed an update which enables you to set MPD's host and port. Just create a file at `~/.mpcbar` and put something like this:

```
[connection]
host = localhost
port = 6600
```

Don't forget to run `brew services restart mpc-bar` afterwards.

I do not have another machine to test with, so let me know if anything does not work as expected.
